title: Mikhail Gubin - DevOps/SRE Engineer
email: vipgubin@list.ru
description: DevOps/SRE-инженер с фокусом на стабильность, безопасность и автоматизацию
baseurl: ""
url: "https://gubin.systems"
github_username: hawk2012

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - devops.pdf
  - devops.txt
  - README.md
  - CNAME

# Custom variables
author:
  name: Mikhail Gubin
  title: DevOps/SRE Engineer
  location: Russia, Yaroslavl
  email: vipgubin@list.ru
  phone: +7 (996) 242-63-65
  telegram: "@sysodmen"
  website: https://gubin.systems
  github: https://github.com/hawk2012
  gitlab: https://gitlab.com/hawk2012
  stackoverflow: https://stackoverflow.com/users/7057373/%d0%9c%d0%b8%d1%85%d0%b0%d0%b8%d0%bb
  habr: https://career.habr.com/mihail-lawyer1989-gubin
  vk: mgubin